cd assimp-5.0.1
IF %ERRORLEVEL% NEQ 0 (EXIT /B %ERRORLEVEL%)

echo "%GENERATOR%"
cmake -Bbuild -G "NMake Makefiles" -DASSIMP_BUILD_TESTS=OFF -DASSIMP_BUILD_SAMPLES=OFF -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DBUILD_SHARED_LIBS=OFF -DASSIMP_NO_EXPORT=OFF -DASSIMP_BUILD_ZLIB=ON -DASSIMP_OPT_BUILD_PACKAGES=OFF -DCMAKE_BUILD_TYPE=Release -DASSIMP_INCLUDE_INSTALL_DIR=%ASSIMPINCLUDESwin% -DASSIMP_LIB_INSTALL_DIR=%ASSIMPLIBSwin%
IF %ERRORLEVEL% NEQ 0 (EXIT /B %ERRORLEVEL%)

cd build
IF %ERRORLEVEL% NEQ 0 (EXIT /B %ERRORLEVEL%)

nmake clean
IF %ERRORLEVEL% NEQ 0 (EXIT /B %ERRORLEVEL%)
nmake
IF %ERRORLEVEL% NEQ 0 (EXIT /B %ERRORLEVEL%)

nmake install
IF %ERRORLEVEL% NEQ 0 (EXIT /B %ERRORLEVEL%)